client_config_backend: settings
client_config:
  client_id: 546811958308-ol3g2grdv09eutl8dt4225e16onrbrni.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
